"""Output Formatter node to compile report JSON and Markdown."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from ..state import PortfolioState

MANDATORY_DISCLAIMER = (
    "**Disclaimer:** This report is generated by an AI research assistant for educational and informational "
    "purposes only. It does not constitute financial, legal, or investment advice. The author is NOT a "
    "SEBI-registered investment advisor. Retail investors should consult a qualified financial advisor before "
    "making any investment decisions. All investments in securities and mutual funds are subject to market risks."
)


def format_output(state: PortfolioState) -> dict[str, Any]:
    """Compile final JSON structure and render Markdown for the advisory report."""
    enriched_holdings = state.get("enriched_holdings") or []
    risk_flags = state.get("risk_flags") or []
    recs_data = state.get("recommendations") or {}
    generated_via = state.get("generated_via") or recs_data.get("generated_via") or "RULE_BASED"

    # 1. Compute summary stats - Filter active vs realized
    active_holdings = [h for h in enriched_holdings if h.get("status") != "REALIZED" and h.get("quantity", 0) > 0]
    realized_holdings = [h for h in enriched_holdings if h.get("status") == "REALIZED" or h.get("quantity", 0) == 0]

    total_val = sum(item.get("value", 0.0) for item in active_holdings)
    sector_weights: dict[str, float] = {}
    for item in active_holdings:
        sec = item.get("sector") or "Unknown"
        sector_weights[sec] = sector_weights.get(sec, 0.0) + item.get("portfolio_weight", 0.0)

    # 2. Compile Report JSON (matching API Contract Response)
    overall_risk = recs_data.get("overall_risk_level", "LOW")
    total_realized_pnl = sum(t.get("realized_pnl", 0.0) for t in realized_holdings)
    
    # 2. Compile Live News (max 5)
    live_news = []
    seen_urls = set()
    
    # First gather news from active holdings
    for h in active_holdings:
        ticker = h.get("ticker", "General")
        for n in h.get("news") or []:
            url = n.get("url")
            if url and url not in seen_urls:
                seen_urls.add(url)
                live_news.append({
                    "ticker": ticker,
                    "title": n.get("title", ""),
                    "url": url,
                    "source": n.get("source", "Market News"),
                    "publishedAt": n.get("published_at") or n.get("publishedAt") or "",
                    "summary": n.get("summary", "")
                })
                if len(live_news) >= 5:
                    break
        if len(live_news) >= 5:
            break
            
    # Fill remaining slots from general market news
    if len(live_news) < 5:
        for n in state.get("market_news") or []:
            url = n.get("url")
            if url and url not in seen_urls:
                seen_urls.add(url)
                live_news.append({
                    "ticker": "MARKET",
                    "title": n.get("title", ""),
                    "url": url,
                    "source": n.get("source", "Indian Share Market"),
                    "publishedAt": n.get("published_at") or n.get("publishedAt") or "",
                    "summary": n.get("summary", "")
                })
                if len(live_news) >= 5:
                    break

    report_json = {
        "id": f"rpt_{uuid.uuid4().hex[:12]}",
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "generatedVia": generated_via,
        "portfolioSummary": {
            "totalValue": round(total_val, 2),
            "holdingsCount": len(active_holdings),
            "overallRiskLevel": overall_risk,
            "sectorAllocation": {k: round(v, 4) for k, v in sector_weights.items()},
            "totalRealizedPnl": round(total_realized_pnl, 2),
            "realizedTradeCount": len(realized_holdings)
        },
        "riskFlags": [
            {
                "ticker": f.get("ticker", "unknown"),
                "flagType": f.get("flag_type", "unknown"),
                "severity": f.get("severity", "MEDIUM"),
                "portfolioWeight": round(f.get("portfolio_weight", 0.0), 4),
                "evidenceText": f.get("evidence_text", ""),
                "citation": f.get("citation", "General Standard")
            }
            for f in risk_flags
        ],
        "recommendations": [
            {
                "ticker": r.get("ticker", "unknown"),
                "action": r.get("action", "HOLD"),
                "priority": r.get("priority", "LOW"),
                "reasoning": r.get("reasoning", ""),
                "citations": r.get("citations", []),
                "disclaimer": r.get("disclaimer", "AI Analysis")
            }
            for r in recs_data.get("recommendations", [])
            if any(h["ticker"] == r.get("ticker") for h in active_holdings) or r.get("ticker") == "PORTFOLIO"
        ],
        "tradeHistory": [
            {
                "ticker": t.get("ticker", "unknown"),
                "name": t.get("name", ""),
                "quantity": t.get("quantity", 0.0),
                "avgBuyPrice": t.get("avg_buy_price", 0.0),
                "sellPrice": t.get("sell_price", 0.0),
                "realizedPnl": t.get("realized_pnl", 0.0)
            }
            for t in realized_holdings
        ],
        "liveNews": live_news,
        "disclaimer": MANDATORY_DISCLAIMER
    }

    # 3. Render Markdown Report
    markdown = render_report_markdown(report_json, enriched_holdings)
    report_json["markdown"] = markdown

    return {
        "report_json": report_json,
        "report_markdown": markdown,
        "current_node": "output"
    }


def render_report_markdown(report: dict[str, Any], holdings: list[dict[str, Any]]) -> str:
    """Helper to construct a beautiful markdown report string."""
    summary = report["portfolioSummary"]
    risk_level = summary["overallRiskLevel"]
    
    active_holdings = [h for h in holdings if h.get("status") != "REALIZED" and h.get("quantity", 0) > 0]
    realized_holdings = report.get("tradeHistory") or []
    
    # Determine risk badge color (GitHub Markdown compatible)
    if risk_level == "HIGH":
        risk_badge = "🔴 **HIGH**"
    elif risk_level == "MEDIUM":
        risk_badge = "🟡 **MEDIUM**"
    else:
        risk_badge = "🟢 **LOW**"

    lines = [
        f"# Portfolio Advisory Report",
        f"*Generated on: {datetime.now(timezone.utc).strftime('%B %d, %Y, %H:%M UTC')} | Method: {report['generatedVia']}*",
        "",
        f"## 1. Executive Summary",
        f"- **Total Portfolio Value:** ₹{summary['totalValue']:,}",
        f"- **Unique Holdings (Active):** {summary['holdingsCount']}",
        f"- **Overall Risk Assessment:** {risk_badge}",
        f"- **Total Realized Profits:** ₹{summary['totalRealizedPnl']:,}",
        f"- **Overview:** {report.get('portfolioSummary') or 'Analysis completed based on dynamic AI analyzer.'}",
        "",
        "## 2. Holdings & Allocation",
        "",
        "| Ticker | Asset Type | Sector/Category | Quantity | Avg Cost | Current Price/NAV | Value | Weight |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for h in active_holdings:
        price_or_nav = h.get("current_price") or h.get("nav") or 0.0
        lines.append(
            f"| **{h['ticker']}** | {h['asset_type']} | {h['sector']} | {h['quantity']:,} | ₹{h['avg_buy_price']:,} | ₹{price_or_nav:,} | ₹{h['value']:,} | {h['portfolio_weight']:.1%} |"
        )
    
    lines.extend([
        "",
        "### Sector Allocation Summary (Active Holdings)",
        "",
        "| Sector/Category | Portfolio Weight |",
        "|---|---|",
    ])
    
    for sec, wt in summary["sectorAllocation"].items():
        lines.append(f"| {sec} | {wt:.1%} |")

    # Add Trade History Section if there are realized trades
    if realized_holdings:
        lines.extend([
            "",
            "### Trade History (Realized/Sold Positions)",
            "",
            "| Ticker | Quantity | Avg Buy Price | Sell Price | Realized Profit/Loss | Status |",
            "|---|---|---|---|---|---|",
        ])
        for t in realized_holdings:
            pnl_val = t["realizedPnl"]
            pnl_str = f"🟢 +₹{pnl_val:,.2f}" if pnl_val >= 0 else f"🔴 -₹{abs(pnl_val):,.2f}"
            lines.append(
                f"| **{t['ticker']}** | {t['quantity']:,} | ₹{t['avgBuyPrice']:,} | ₹{t['sellPrice']:,} | {pnl_str} | REALIZED |"
            )

    # Add Risk Flags Section
    lines.extend([
        "",
        "## 3. Identified Regulatory & Financial Risks",
        "",
    ])
    
    if not report["riskFlags"]:
        lines.append("✓ **No significant risk flags identified.** Your portfolio aligns with general retail investor guidelines.")
    else:
        lines.extend([
            "| Asset/Sector | Risk Type | Severity | Evidence | Citation |",
            "|---|---|---|---|---|",
        ])
        for f in report["riskFlags"]:
            sev_str = "🔴 HIGH" if f["severity"] == "HIGH" else "🟡 MEDIUM" if f["severity"] == "MEDIUM" else "🟢 LOW"
            lines.append(
                f"| **{f['ticker']}** | {f['flagType'].replace('_', ' ')} | {sev_str} | {f['evidenceText']} | *{f['citation']}* |"
            )

    # Add Recommendations Section
    lines.extend([
        "",
        "## 4. Actionable Advisory Recommendations",
        "",
    ])
    
    for r in report["recommendations"]:
        action = r["action"]
        badge = "🔴 EXIT" if action == "EXIT" else "🟡 TRIM" if action == "TRIM" else "🟢 BUY" if action == "BUY" else "🔵 HOLD"
        priority_str = "🔥 High" if r["priority"] == "HIGH" else "⚡ Medium" if r["priority"] == "MEDIUM" else "💤 Low"
        
        lines.extend([
            f"### {badge} — {r['ticker']}",
            f"- **Action Priority:** {priority_str}",
            f"- **Reasoning:** {r['reasoning']}",
        ])
        if r["citations"]:
            lines.append(f"- **Citations:** {', '.join([f'*{c}*' for c in r['citations']])}")
        lines.append("")

    # Add Live News Section
    live_news = report.get("liveNews") or []
    if live_news:
        lines.extend([
            "",
            "## 5. Live Market News",
            "",
        ])
        for item in live_news:
            source_str = f" (*Source: {item['source']}*)" if item.get('source') else ""
            date_str = f" - {item['publishedAt'][:10]}" if item.get('publishedAt') else ""
            lines.append(
                f"- **[{item['ticker']}]** [{item['title']}]({item['url']}){source_str}{date_str}"
            )
        lines.append("")

    # Add Disclaimer Section
    lines.extend([
        "---",
        "## 6. Regulatory Disclaimers & Disclosures",
        "",
        MANDATORY_DISCLAIMER,
        ""
    ])

    return "\n".join(lines)
