services:
  web:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - ai
    networks:
      - finance-agent

  ai:
    build:
      context: ./ai-service
    env_file:
      - ./ai-service/.env
    ports:
      - "8000:8000"
    networks:
      - finance-agent

networks:
  finance-agent:
    driver: bridge
