"""Application constants for the AI service."""

MAX_MEMORY_MB = 480
REPORT_RATE_LIMIT_PER_MINUTE = 10
QA_RATE_LIMIT_PER_MINUTE = 30
DEFAULT_CACHE_TTL_SECONDS = 3600
STOCK_QUOTE_CACHE_TTL_SECONDS = 900
STOCK_FUNDAMENTALS_CACHE_TTL_SECONDS = 86400
STOCK_NEWS_CACHE_TTL_SECONDS = 7200
MF_NAV_CACHE_TTL_SECONDS = 14400
MF_METADATA_CACHE_TTL_SECONDS = 86400
MF_HOLDINGS_CACHE_TTL_SECONDS = 86400
MACRO_CACHE_TTL_SECONDS = 21600
GROQ_FAILURE_THRESHOLD = 3
GROQ_CIRCUIT_RESET_SECONDS = 300
TEMP_FILE_TTL_SECONDS = 600
MAX_PDF_SIZE_BYTES = 5 * 1024 * 1024
INTERNAL_API_HEADER = "X-Internal-Key"
SESSION_COOKIE_NAME = "portfolio_session"
SQLITE_CACHE_TABLE = "api_cache"
SQLITE_CHECKPOINT_TABLE = "agent_checkpoints"
